name: Backend Tests

on:
  push:
    # Tests run automatically when pushing to these branches
    branches:
      - ci/github-actions-pipeline
      - develop
      - main
      
  pull_request:
    # Tests run when creating a Pull Request TARGETING these branches
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: 📦 Installation des dépendances
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx PyJWT python-multipart PyMuPDF openai sentence-transformers

      - name: 🧪 Run tests with Pytest
        working-directory: ./backend
        run: |
          pytest tests/ -v